### ISSUE TITLE
Failed to parse `git status` result when it has leading comment character

### ISSUE THREAD

**Issue by kiooss** [lambdalisue/gina.vim#159]
When open a gina-status buffer by `:Gina status` , the mappings such as `<<`, `>>` not working.
While these mappings work in gina-status buffer opened by `:Gina status -s`.

I tried the latest gina.

**Comment by lambdalisue** [comment]
I could not reproduce. Are you sure that the cursor is on `modified: ...` line like the screenshot below?

<img width="898" alt="alacritty 2018-03-21 13-37-04" src="https://user-images.githubusercontent.com/546312/37694750-f357a816-2d0c-11e8-86fa-aae246115ec0.png">

**Comment by kiooss** [comment]
I made an asciinema video, and reproduced the issue with a minimal vimrc.

https://asciinema.org/a/30VCS2dR3tliDyltQPU4PkO05

**Comment by lambdalisue** [comment]
Got it. It's because gina failed to parse the result of `git status` while it includes Japanese.

I'll fix it thanks 👍

**Comment by lambdalisue** [comment]
Do you know how to enable Japanese output in git?

**Comment by lambdalisue** [comment]
And could you try if `LANG=C git status` shows English version?

**Comment by kiooss** [comment]
`LANG=C git status` doesn't show English version while `LC_ALL=C git status ` does in my machine.

**Comment by lambdalisue** [comment]
> LANG=C git status doesn't show English version while LC_ALL=C git status does in my machine.

Good news thanks. I'll use `LC_ALL` instead

**Comment by kiooss** [comment]
It looks like `LANGUAGE` has the highest priority. `LANGUAGE=ja_JP.UTF-8 git status` will show Japanese version and `LANGUAGE=C git status` will show English version.

**Comment by lambdalisue** [comment]
Could you try if https://github.com/lambdalisue/gina.vim/pull/160 fixes the issue?

**Comment by lambdalisue** [comment]
Wait. It seems `LC_ALL` should be used https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html#The-LANGUAGE-variable

**Comment by lambdalisue** [comment]
Fixed. Could you try?

**Comment by kiooss** [comment]
Tried #160, unfortunately the problem still exists.
The `git status` output is like below:

```
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       minimal.vim
#
nothing added to commit but untracked files present (use "git add" to track)
```

Maybe it's not because Japanese char, the char `#` in the beginning of the line cause parse failed?

**Comment by lambdalisue** [comment]
> Maybe it's not because Japanese char, the char # in the beginning of the line cause parse failed?

Probably. What kind of config causes the leading `#` in your git status?

**Comment by kiooss** [comment]
Yes, it looks like `#` cause the issue. I made the buffer modifiable, then delete the `#`, and everything works.

**Comment by kiooss** [comment]
I did not config it, and I have no idea how to config it not show `#`.
The git version is `git version 2.11.0`, and the os is `Ubuntu 16.04.4 LTS`. The git is installed by `apt`.

**Comment by kiooss** [comment]
Addition info is that `vim-fugitive`'s `:Gstatus` works well in this case.

**Comment by lambdalisue** [comment]
It seems some has leading `#`

https://www.google.co.jp/search?q=git+status&client=firefox-b-ab&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwivtuXO-PzZAhUKXLwKHapeALsQ_AUICigB&biw=1408&bih=1205#imgrc=_

I'll support it 👍

**Comment by lambdalisue** [comment]
Could you try #161?

**Comment by kiooss** [comment]
> Could you try #161?

Not working.

**Comment by lambdalisue** [comment]
Did you try https://github.com/lambdalisue/gina.vim/pull/161/commits/5ee2c1bb4e7c29ce5666aca5cde46d9dd32584b9? I fixed the PR.

**Comment by kiooss** [comment]
> Did you try 5ee2c1b? I fixed the PR.

Yeah, it works! 👍

**Comment by lambdalisue** [comment]
Awesome!
I'll merge it soon
